version: "3"

vars:
  GARAGE_REPO: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  GARAGE_SOURCE_PATH: script/helm/garage
  GARAGE_TARGET_PATH: manifests/garage
  GARAGE_TMP_PATH: .tmp/garage

includes:
  apps:
    taskfile: ./apps/Taskfile.yaml
    dir: ./apps/

tasks: {}
