apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drewysq-mywire-org-homepage
spec:
  # Secret names are always required.
  secretName: drewysq-mywire-org-homepage-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - drewysq.mywire.org
