apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-loki
  namespace: garage
spec:
  refreshPolicy: CreatedOnce

  target:
    name: garage-loki
    creationPolicy: Orphan
    immutable: true

    template:
      type: Opaque
      engineVersion: v2
      data:
        access-key: "GK{{ .keyId }}"
        secret-key: "{{ .secretKey }}"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: garage-loki-access-key

    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: garage-loki-secret-key
