apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: garage-loki-secret-key
  namespace: garage
spec:
  length: 64
  encoding: hex
  allowRepeat: true
  secretKeys:
    - secretKey
